export interface Translations {
  appName: string;
  tagline: string;
  search: string;
  filter: string;
  all: string;
  add: string;
  save: string;
  edit: string;
  delete: string;
  cancel: string;
  title: string;
  notes: string;
  actions: string;
  close: string;
  completed: string;
  
  // Sidebar / Modules
  dashboard: string;
  ideaVault: string;
  scriptWriter: string;
  analytics: string;
  calendar: string;
  goals: string;
  seriesManager: string;
  abTesting: string;
  seoHelper: string;
  settings: string;

  // Idea Vault
  newIdea: string;
  editIdea: string;
  ideaTitle: string;
  oneLineHook: string;
  priority: string;
  status: string;
  tagsPlaceholder: string;
  linksPlaceholder: string;
  noIdeasYet: string;
  convertToScript: string;
  kanbanView: string;
  listView: string;
  hot: string;
  warm: string;
  cold: string;
  
  // Video Statuses
  status_idea: string;
  status_scripting: string;
  status_ready_to_film: string;
  status_filmed: string;
  status_editing: string;
  status_published: string;
  status_archived: string;

  // Script Writer
  noScriptYet: string;
  writeScriptFor: string;
  sectionHook: string;
  sectionIntro: string;
  sectionMainPoints: string;
  sectionCTA: string;
  sectionOutro: string;
  wordCount: string;
  estRuntime: string;
  speakingPace: string;
  autosaved: string;
  versionHistory: string;
  restore: string;
  currentVersion: string;
  linkToIdea: string;

  // Analytics
  analyticsDashboard: string;
  subscribers: string;
  totalViews: string;
  watchTimeHours: string;
  revenue: string;
  uploadFrequency: string;
  topPerformingVideos: string;
  plannedVsActual: string;
  subscribersOverTime: string;
  performanceFlag: string;
  underperformed: string;
  excellent: string;
  normal: string;
  addVideoStats: string;
  targetViews: string;
  likes: string;
  comments: string;
  publishDate: string;
  manualStatsEntry: string;
  updateStats: string;

  // Calendar
  calendarOverview: string;
  dragDropSchedule: string;
  prevMonth: string;
  nextMonth: string;
  today: string;
  unscheduledIdeas: string;
  scheduleIdea: string;

  // Goals
  goalTracker: string;
  activeGoals: string;
  addGoal: string;
  goalTitle: string;
  goalCategory: string;
  targetValue: string;
  currentValue: string;
  deadline: string;
  uploadStreak: string;
  streakDays: string;
  streakActive: string;
  weeklyReview: string;
  autoGeneratedSummary: string;
  noGoalsYet: string;
  cadenceGoal: string;

  // Checklist / Task Manager
  checklist: string;
  addChecklistItem: string;
  tasksCompleted: string;

  // SEO & Pillars
  pillarsAndSeries: string;
  createSeries: string;
  seriesName: string;
  seriesColor: string;
  abNotes: string;
  abNotesPlaceholder: string;
  titleVariants: string;
  thumbnailA_B: string;
  seoHelperTitle: string;
  keywords: string;
  descriptionTemplate: string;
  addKeyword: string;

  // General Settings
  theme: string;
  lightMode: string;
  darkMode: string;
  language: string;
  exportData: string;
  importData: string;
  persianNumerals: string;
  exportSuccess: string;
  importSuccess: string;
  wpmLabel: string;
  backupDatabase: string;
  quickStats: string;
  lastVideoPerf: string;
  nextScheduled: string;
  none: string;
}

export const translations: { en: Translations; fa: Translations } = {
  en: {
    appName: 'Creo',
    tagline: 'YouTube Channel Manager',
    search: 'Search...',
    filter: 'Filter',
    all: 'All',
    add: 'Add',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    title: 'Title',
    notes: 'Notes',
    actions: 'Actions',
    close: 'Close',
    completed: 'Completed',

    dashboard: 'Dashboard',
    ideaVault: 'Idea Vault',
    scriptWriter: 'Script Writer',
    analytics: 'Analytics',
    calendar: 'Calendar',
    goals: 'Goals',
    seriesManager: 'Series & Pillars',
    abTesting: 'Title & Thumb A/B',
    seoHelper: 'SEO Assistant',
    settings: 'Settings',

    newIdea: 'New Idea',
    editIdea: 'Edit Idea',
    ideaTitle: 'Video Title / Idea Name',
    oneLineHook: 'One-Line Hook (The Core Hook)',
    priority: 'Priority',
    status: 'Status',
    tagsPlaceholder: 'Tags (comma separated)',
    linksPlaceholder: 'Reference Links (comma separated)',
    noIdeasYet: 'No ideas in this column. Tap "New Idea" to capture one!',
    convertToScript: 'Convert to Script',
    kanbanView: 'Kanban Board',
    listView: 'List View',
    hot: 'Hot 🔥',
    warm: 'Warm ⚡',
    cold: 'Cold ❄️',

    status_idea: 'Idea',
    status_scripting: 'Scripting',
    status_ready_to_film: 'Ready to Film',
    status_filmed: 'Filmed',
    status_editing: 'Editing',
    status_published: 'Published',
    status_archived: 'Archived',

    noScriptYet: 'No script found for this idea. Click "Convert to Script" in the Idea Vault to begin writing!',
    writeScriptFor: 'Writing Script for',
    sectionHook: '1. Hook (First 15 Seconds)',
    sectionIntro: '2. Introduction (Set expectations)',
    sectionMainPoints: '3. Main Points (Value & Content)',
    sectionCTA: '4. Call to Action (Subscribe / Next Video)',
    sectionOutro: '5. Outro (Final closing thoughts)',
    wordCount: 'Word Count',
    estRuntime: 'Est. Runtime',
    speakingPace: 'Pace (WPM)',
    autosaved: 'Autosaved',
    versionHistory: 'Version History',
    restore: 'Restore',
    currentVersion: 'Current Version',
    linkToIdea: 'Link back to Idea',

    analyticsDashboard: 'Channel Analytics Dashboard',
    subscribers: 'Subscribers',
    totalViews: 'Total Views',
    watchTimeHours: 'Watch Time (Hrs)',
    revenue: 'Estimated Revenue',
    uploadFrequency: 'Upload Frequency (Last 4 Weeks)',
    topPerformingVideos: 'Top Performing Videos',
    plannedVsActual: 'Planned vs. Actual Performance',
    subscribersOverTime: 'Subscribers Growth Over Time',
    performanceFlag: 'Performance evaluation',
    underperformed: 'Underperformed',
    excellent: 'Excellent (Beat target!)',
    normal: 'As Expected',
    addVideoStats: 'Add Video Performance Stat',
    targetViews: 'Target Views',
    likes: 'Likes',
    comments: 'Comments',
    publishDate: 'Publish Date',
    manualStatsEntry: 'Manual Entry (YouTube Sync is ready to activate)',
    updateStats: 'Update Channel Stats',

    calendarOverview: 'Content Publication Calendar',
    dragDropSchedule: 'Click on a day or draft an idea to schedule its release date.',
    prevMonth: 'Previous',
    nextMonth: 'Next',
    today: 'Today',
    unscheduledIdeas: 'Unscheduled Ideas',
    scheduleIdea: 'Schedule Release',

    goalTracker: 'Channel Goals & Milestones',
    activeGoals: 'Active Goals',
    addGoal: 'Create New Goal',
    goalTitle: 'Goal Objective',
    goalCategory: 'Category',
    targetValue: 'Target Metric',
    currentValue: 'Current Value',
    deadline: 'Deadline',
    uploadStreak: 'Consistency Streak',
    streakDays: 'Upload Streak (Days)',
    streakActive: 'Streak Active!',
    weeklyReview: 'Weekly Channel Review',
    autoGeneratedSummary: 'Weekly Summary & AI Recommendations',
    noGoalsYet: 'No goals defined yet. Let\'s outline some milestones!',
    cadenceGoal: 'Cadence (Videos per week)',

    checklist: 'Video Task Checklist',
    addChecklistItem: 'Add Task...',
    tasksCompleted: 'Tasks Completed',

    pillarsAndSeries: 'Content Pillars & Series',
    createSeries: 'Create Series / Pillar',
    seriesName: 'Series Name',
    seriesColor: 'Color Theme',
    abNotes: 'A/B Testing Notes',
    abNotesPlaceholder: 'Write observations about CTR, thumbnail contrast, variations...',
    titleVariants: 'Title A/B Testing Variants',
    thumbnailA_B: 'Thumbnail Design A/B Notes',
    seoHelperTitle: 'SEO & Description Metadata',
    keywords: 'Target Keywords',
    descriptionTemplate: 'Description Outline Template',
    addKeyword: 'Add keyword...',

    theme: 'App Theme',
    lightMode: 'Light Theme',
    darkMode: 'Dark Theme',
    language: 'App Language',
    exportData: 'Export Backup (JSON/SQLite format)',
    importData: 'Import Backup',
    persianNumerals: 'Convert to Persian Numerals',
    exportSuccess: 'Backup data successfully copied to clipboard or downloaded!',
    importSuccess: 'Backup data successfully restored!',
    wpmLabel: 'Average Speaking WPM',
    backupDatabase: 'Backup Database',
    quickStats: 'Quick Stats Snapshot',
    lastVideoPerf: 'Last Upload Performance',
    nextScheduled: 'Next Upload Scheduled',
    none: 'None',
  },
  fa: {
    appName: 'کریو (Creo)',
    tagline: 'مدیریت حرفه‌ای کانال یوتیوب',
    search: 'جستجو...',
    filter: 'فیلتر',
    all: 'همه',
    add: 'افزودن',
    save: 'ذخیره',
    edit: 'ویرایش',
    delete: 'حذف',
    cancel: 'لغو',
    title: 'عنوان',
    notes: 'یادداشت‌ها',
    actions: 'عملیات',
    close: 'بستن',
    completed: 'تکمیل شده',

    dashboard: 'داشبورد',
    ideaVault: 'صندوق ایده‌ها',
    scriptWriter: 'نویسنده سناریو',
    analytics: 'آنالیز کانال',
    calendar: 'تقویم محتوایی',
    goals: 'اهداف و پیشرفت',
    seriesManager: 'ستون‌های محتوایی',
    abTesting: 'تست عنوان و کاور',
    seoHelper: 'کمک‌یار سئو (SEO)',
    settings: 'تنظیمات',

    newIdea: 'ایده جدید',
    editIdea: 'ویرایش ایده',
    ideaTitle: 'عنوان ویدیو / نام ایده',
    oneLineHook: 'قلاب تک‌خطی (Hook اصلی)',
    priority: 'اولویت',
    status: 'وضعیت',
    tagsPlaceholder: 'برچسب‌ها (با کاما جدا کنید)',
    linksPlaceholder: 'لینک‌های مرجع (با کاما جدا کنید)',
    noIdeasYet: 'هیچ ایده‌ای در این ستون نیست. برای ثبت اولین ایده روی دکمه "ایده جدید" ضربه بزنید!',
    convertToScript: 'تبدیل به سناریو',
    kanbanView: 'نمای کانبان',
    listView: 'نمای لیستی',
    hot: 'داغ 🔥',
    warm: 'گرم ⚡',
    cold: 'سرد ❄️',

    status_idea: 'ایده خام',
    status_scripting: 'در حال نگارش',
    status_ready_to_film: 'آماده ضبط',
    status_filmed: 'ضبط شده',
    status_editing: 'در حال تدوین',
    status_published: 'منتشر شده',
    status_archived: 'بایگانی شده',

    noScriptYet: 'هیچ سناریویی برای این ایده ثبت نشده است. در بخش صندوق ایده‌ها روی "تبدیل به سناریو" کلیک کنید تا نوشتن را آغاز کنید!',
    writeScriptFor: 'نگارش سناریو برای',
    sectionHook: '۱. قلاب (۱۵ ثانیه اول)',
    sectionIntro: '۲. معرفی (ایجاد انتظار در بیننده)',
    sectionMainPoints: '۳. بخش اصلی (ارزش و محتوا)',
    sectionCTA: '۴. دعوت به اقدام (سابسکرایب / ویدیوی بعدی)',
    sectionOutro: '۵. پایان‌بندی (جمع‌بندی نهایی)',
    wordCount: 'تعداد کلمات',
    estRuntime: 'زمان تخمینی ویدیو',
    speakingPace: 'سرعت گویش (WPM)',
    autosaved: 'ذخیره خودکار انجام شد',
    versionHistory: 'تاریخچه نسخه‌ها',
    restore: 'بازیابی نسخه',
    currentVersion: 'نسخه فعلی',
    linkToIdea: 'بازگشت به ایده مبدا',

    analyticsDashboard: 'داشبورد تجزیه و تحلیل کانال',
    subscribers: 'سابسکرایبرها',
    totalViews: 'کل بازدیدها',
    watchTimeHours: 'زمان تماشا (ساعت)',
    revenue: 'درآمد تخمینی (دلار)',
    uploadFrequency: 'فرکانس آپلود (۴ هفته اخیر)',
    topPerformingVideos: 'ویدیوهای برتر',
    plannedVsActual: 'عملکرد برنامه‌ریزی شده در مقابل واقعی',
    subscribersOverTime: 'روند رشد سابسکرایبر',
    performanceFlag: 'ارزیابی عملکرد',
    underperformed: 'کمتر از حد انتظار',
    excellent: 'عالی (فراتر از هدف!)',
    normal: 'مطابق انتظار',
    addVideoStats: 'افزودن آمار ویدیو جدید',
    targetViews: 'تارگت بازدید (هدف)',
    likes: 'لایک‌ها',
    comments: 'کامنت‌ها',
    publishDate: 'تاریخ انتشار',
    manualStatsEntry: 'ثبت دستی آمار (همگام‌سازی خودکار یوتیوب آماده فعال‌سازی)',
    updateStats: 'بروزرسانی آمار کانال',

    calendarOverview: 'تقویم انتشار محتوا',
    dragDropSchedule: 'روی یک روز کلیک کنید یا یک ایده از لیست پیش‌نویس‌ها انتخاب کنید تا زمان انتشار آن را تنظیم کنید.',
    prevMonth: 'ماه قبل',
    nextMonth: 'ماه بعد',
    today: 'امروز',
    unscheduledIdeas: 'ایده‌های بدون زمان‌بندی',
    scheduleIdea: 'برنامه‌ریزی انتشار',

    goalTracker: 'اهداف و نقاط عطف کانال',
    activeGoals: 'اهداف فعال شما',
    addGoal: 'تعریف هدف جدید',
    goalTitle: 'عنوان هدف',
    goalCategory: 'دسته‌بندی',
    targetValue: 'هدف عددی (Metric)',
    currentValue: 'مقدار فعلی',
    deadline: 'مهلت نهایی',
    uploadStreak: 'رکورد تداوم آپلود',
    streakDays: 'تعداد روز تداوم (Streak)',
    streakActive: 'رکورد تداوم فعال است!',
    weeklyReview: 'بررسی هفتگی عملکرد کانال',
    autoGeneratedSummary: 'خلاصه عملکرد هفتگی و توصیه‌های هوشمند',
    noGoalsYet: 'هنوز هدفی تعریف نکرده‌اید. بیایید چند نقطه عطف زیبا برای کانال تعریف کنیم!',
    cadenceGoal: 'فرکانس آپلود (ویدیو در هفته)',

    checklist: 'چک‌لیست کارهای هر ویدیو',
    addChecklistItem: 'افزودن کار...',
    tasksCompleted: 'کارهای تکمیل شده',

    pillarsAndSeries: 'ستون‌های محتوایی و سری‌ها',
    createSeries: 'ایجاد ستون محتوایی جدید',
    seriesName: 'نام سری / ستون محتوایی',
    seriesColor: 'رنگ اختصاصی',
    abNotes: 'یادداشت‌های تست A/B',
    abNotesPlaceholder: 'مشاهدات خود را در مورد نرخ کلیک (CTR)، تضاد رنگ کاور، عناوین متفاوت و غیره یادداشت کنید...',
    titleVariants: 'تست A/B عناوین پیشنهادی',
    thumbnailA_B: 'تست و ارزیابی کاور (تامبنیل)',
    seoHelperTitle: 'متادیتا و تنظیمات سئو ویدیو',
    keywords: 'کلمات کلیدی هدف',
    descriptionTemplate: 'الگوی ساختاریافته توضیحات (Description)',
    addKeyword: 'افزودن کلمه کلیدی...',

    theme: 'پوسته نرم‌افزار',
    lightMode: 'پوسته روشن',
    darkMode: 'پوسته تاریک',
    language: 'زبان نرم‌افزار',
    exportData: 'خروجی پشتیبان (فرمت JSON/SQLite)',
    importData: 'وارد کردن پشتیبان',
    persianNumerals: 'تبدیل اعداد به فارسی',
    exportSuccess: 'فایل پشتیبان با موفقیت کپی یا دانلود شد!',
    importSuccess: 'داده‌های پشتیبان با موفقیت بازیابی شدند!',
    wpmLabel: 'سرعت متوسط خوانش (کلمه در دقیقه)',
    backupDatabase: 'پشتیبان‌گیری',
    quickStats: 'خلاصه وضعیت کانال',
    lastVideoPerf: 'عملکرد آخرین آپلود',
    nextScheduled: 'ویدیوی زمان‌بندی‌شده بعدی',
    none: 'هیچ‌کدام',
  },
};

// Converts numbers to Persian format if requested
export function toPersianDigits(num: number | string, active: boolean): string {
  if (!active) return num.toString();
  const id = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];
  return num.toString().replace(/[0-9]/g, function (w) {
    return id[+w];
  });
}
